import numpy as np
import torchvision
from torchvision import transforms
import torch

#Parameters are placed below
save_root=...

targets = [...]
meme_sizes={...}
target_channels={...}
target_stride={...}

capacity = ...
keep_channel =  ...

batch_size = ...
extract_iter = ...
prune_iter = ...
p = ...



train_dataset = ...
test_dataset = ...

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=False)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          shuffle=False)
#Hyper-parameters are placed below
log=...

num_channels = ...
num_labels = ...

momentum = ...
origin_interval = ...
